version: "3"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: local
      args:
        GOLANG_IMAGE_TAG: "1.21.1-alpine"
    image: echo-rest-web
    container_name: echo-rest-web
    tty: true
    volumes:
      - ./web:/app
    working_dir: /app
    ports:
      - "8080:8080"

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
      args:
        POSTGRESQL_IMAGE_TAG: "16.0-alpine3.18"
    image: echo-rest-db
    container_name: echo-rest-db
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data/
    env_file:
      - ./db/.env
