version: "3"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: local
      args:
        GOLANG_IMAGE_TAG: "1.21.1-alpine"
    image: echo-rest-web
    container_name: echo-rest-web
    tty: true
    volumes:
      - ./web:/app
    working_dir: /app
    ports:
      - "8080:8080"
